In [2]:
import numpy as np


In [27]:
random_array = np.random.randint(1,51,size=10)
random_array

array([30, 29, 39, 16, 42, 44, 32, 50, 11,  8], dtype=int32)

In [28]:
np.mean(random_array)

np.float64(30.1)

In [21]:
arr1=[[1,2,3],[1,2,3]]
arr2=[[1,2,3],[1,2,3]]
arr3=np.add(arr1 , arr2)
arr3

array([[2, 4, 6],
       [2, 4, 6]])

In [22]:
np.mean(arr3)

np.float64(4.0)

In [19]:
arr4

array([[2, 4, 6],
       [2, 4, 6]])

In [26]:
random_array2 = np.random.randint(1,101,size=20)
random_array2

array([20, 26, 85, 87, 65, 99, 19, 21, 10, 35, 25, 34, 79, 97, 87, 34, 31,
       79, 66, 67], dtype=int32)

In [29]:
greater_than_50 = random_array2[random_array2 > 50]
greater_than_50

array([85, 87, 65, 99, 79, 97, 87, 79, 66, 67], dtype=int32)

In [ ]:
arr5=np.arange(1, 11)
np.random.shuffle(arr5)
random_elements = np.random.choice(arr, 3, replace=False)
